//
//  Image+DinotisIcon.swift
//  
//
//  Created by Gus Adi on 01/12/22.
//

import SwiftUI

public extension Image {
    static let generalBackIcon = Image("ic-back-general", bundle: Bundle.module)
    static let generalQuestionIcon = Image("ic-question-general", bundle: Bundle.module)
    static let logoWithText = Image("logo-with-text", bundle: Bundle.module)
    static let logoWhiteText = Image("logo-white-text", bundle: .module)
    
    static let talentProfileGmailIcon = Image("ic-gmail-talent-profile", bundle: Bundle.module)
    static let talentProfileInstagramIcon = Image("ic-instagram-talent-profile", bundle: Bundle.module)
    static let talentProfileLinkedinIcon = Image("ic-linkedin-talent-profile", bundle: Bundle.module)
    static let talentProfileTiktokIcon = Image("ic-tiktok-talent-profile", bundle: Bundle.module)
    static let talentProfileTwitterIcon = Image("ic-twitter-talent-profile", bundle: Bundle.module)
    static let talentProfileWebIcon = Image("ic-web-talent-profile", bundle: Bundle.module)
    static let talentProfileShareIcon = Image("ic-share-talent-profile", bundle: Bundle.module)
    static let talentProfileWhatsappIcon = Image("ic-whatsapp-talent-profile", bundle: Bundle.module)
    static let talentProfileManagementIcon = Image("ic-management-talent-profile", bundle: Bundle.module)
    static let talentProfileStarIcon = Image("ic-star-talent-profile", bundle: Bundle.module)
    static let talentProfileAttentionIcon = Image("ic-attention-talent-profile", bundle: Bundle.module)
    
    static let notificationIcon = Image("ic-notification", bundle: Bundle.module)
    static let notificationSolidIcon = Image("ic-solid-notification", bundle: Bundle.module)
    
    static let otpSmsIcon = Image("ic-sms-otp", bundle: Bundle.module)
    static let otpWhatsappIcon = Image("ic-whatsapp-otp", bundle: Bundle.module)
    
    static let bottomNavigationExplorePurpleIcon = Image("ic-explore-purple-bottom-navigation", bundle: Bundle.module)
    static let bottomNavigationExploreWhiteIcon = Image("ic-explore-white-bottom-navigation", bundle: Bundle.module)
    static let bottomNavigationProfilePurpleIcon = Image("ic-profile-purple-bottom-navigation", bundle: Bundle.module)
    static let bottomNavigationProfileWhiteIcon = Image("ic-profile-white-bottom-navigation", bundle: Bundle.module)
    static let bottomNavigationVideoPurpleIcon = Image("ic-schedule-video-purple-bottom-navigation", bundle: Bundle.module)
    static let bottomNavigationVideoWhiteIcon = Image("ic-schedule-video-white-bottom-navigation", bundle: Bundle.module)
    static let bottomNavigationSearchPurpleIcon = Image("ic-search-purple-bottom-navigation", bundle: Bundle.module)
    static let bottomNavigationSearchWhiteIcon = Image("ic-search-white-bottom-navigation", bundle: Bundle.module)
    
    
    static let messageSendIcon = Image("ic-send-message", bundle: Bundle.module)
    
    static let profileChangePassIcon = Image("ic-changepass-profile", bundle: Bundle.module)
    static let profileEditIcon = Image("ic-editprofile-profile", bundle: Bundle.module)
    static let profileFavoriteIcon = Image("ic-favorite-profile", bundle: Bundle.module)
    static let profileHelpIcon = Image("ic-help-profile", bundle: Bundle.module)
    static let profileLogoutIcon = Image("ic-logout-profile", bundle: Bundle.module)
    
    static let paymentBCAIcon = Image("ic-bca-payment", bundle: Bundle.module)
    static let paymentBNIIcon = Image("ic-bni-payment", bundle: Bundle.module)
    static let paymentBrivaIcon = Image("ic-briva-payment", bundle: Bundle.module)
    static let paymentBTNIcon = Image("ic-btn-payment", bundle: Bundle.module)
    static let paymentGopayIcon = Image("ic-gopay-payment", bundle: Bundle.module)
    static let paymentLinkajaIcon = Image("ic-linkaja-payment", bundle: Bundle.module)
    static let paymentMandiriIcon = Image("ic-mandiri-payment", bundle: Bundle.module)
    static let paymentOvoIcon = Image("ic-ovo-payment", bundle: Bundle.module)
    static let paymentQrisIcon = Image("ic-qris-payment", bundle: Bundle.module)
    static let paymentShopeepayIcon = Image("ic-shopeepay-payment", bundle: Bundle.module)
	static let paymentAppleIcon = Image("ic-apple-logo", bundle:  .module)
    
    static let sessionCardCameraIcon = Image("ic-camera-session-card", bundle: Bundle.module)
    static let sessionCardCoinIcon = Image("ic-coin-session-card", bundle: Bundle.module)
    static let sessionCardDateIcon = Image("ic-date-session-card", bundle: Bundle.module)
    static let sessionCardElectricIcon = Image("ic-electric-session-card", bundle: Bundle.module)
    static let sessionCardListSolidIcon = Image("ic-list-solid-session-card", bundle: Bundle.module)
    static let sessionCardNotesSolidIcon = Image("ic-notes-solid-session-card", bundle: Bundle.module)
    static let sessionCardPersonSolidIcon = Image("ic-person-solid-session-card", bundle: Bundle.module)
    static let sessionCardPricetagIcon = Image("ic-pricetag-session-card", bundle: Bundle.module)
    static let sessionCardRedPricetagSolidIcon = Image("ic-red-pricetag-solid-session-card", bundle: Bundle.module)
    static let sessionCardYellowPricetagSolidIcon = Image("ic-yellow-pricetag-solid-session-card", bundle: Bundle.module)
    static let sessionCardSessionTypeSolidIcon = Image("ic-sessiontype-solid-session-card", bundle: Bundle.module)
    static let sessionCardTimeSolidIcon = Image("ic-time-solid-session-card", bundle: Bundle.module)
    static let sessionCardVerifiedIcon = Image("ic-verified-session-card", bundle: Bundle.module)
    static let sessionCardVideoSolidIcon = Image("ic-video-solid-session-card", bundle: Bundle.module)
    static let sessionCardVideocallIcon = Image("ic-videocall-session-card", bundle: Bundle.module)
    
    static let coinBalanceIcon = Image("ic-balance-coin", bundle: Bundle.module)
    static let coinHistoryIcon = Image("ic-history-coin", bundle: Bundle.module)
    static let coinInIcon = Image("ic-in-coin", bundle: Bundle.module)
    static let coinOutIcon = Image("ic-out-coin", bundle: Bundle.module)
    
    static let filterCameraIcon = Image("ic-camera-filter", bundle: Bundle.module)
    static let filterChatIcon = Image("ic-chat-filter", bundle: Bundle.module)
    static let filterDiscussIcon = Image("ic-discuss-filter", bundle: Bundle.module)
    static let filterFireIcon = Image("ic-fire-filter", bundle: Bundle.module)
    static let filterGiftIcon = Image("ic-gift-filter", bundle: Bundle.module)
    
    static let sessionDetailChevronIcon = Image("ic-chevron-session-detail", bundle: Bundle.module)
    static let sessionDetailActiveCheckmarkIcon = Image("ic-active-checkmark-session-detail", bundle: Bundle.module)
    static let sessionDetailInactiveCheckmarkIcon = Image("ic-inactive-checkmark-session-detail", bundle: Bundle.module)
    static let sessionDetailXmarkIcon = Image("ic-xmark-session-detail", bundle: Bundle.module)
    static let icDocumentSessionDetail = Image("ic-document-session-detail", bundle: Bundle.module)
    static let icGlobeSessionDetail = Image("ic-globe-session-detail", bundle: Bundle.module)
    
    static let searchPersonIcon = Image("ic-person-search", bundle: Bundle.module)
    static let searchVideoIcon = Image("ic-video-search", bundle: Bundle.module)
    
    static let videoCallChatActiveIcon = Image("ic_chat_active", bundle: .module)
    static let videoCallChatInactiveIcon = Image("ic_chat_inactive", bundle: .module)
    static let videoCallOtherMenuActiveIcon = Image("ic_grid_active", bundle: .module)
    static let videoCallOtherMenuInactiveIcon = Image("ic_grid_inactive", bundle: .module)
    static let videoCallRaiseHandActiveIcon = Image("ic_hand_active", bundle: .module)
    static let videoCallRaiseHandInactiveIcon = Image("ic_hand_inactive", bundle: .module)
    static let videoCallMenuActiveIcon = Image("ic_menu_active", bundle: .module)
    static let videoCallMenuInactiveIcon = Image("ic_menu_inactive", bundle: .module)
    static let videoCallMicrophoneActiveIcon = Image("ic_mic_active", bundle: .module)
    static let videoCallMicrophoneInactiveIcon = Image("ic_mic_inactive", bundle: .module)
    static let videoCallParticipantActiveIcon = Image("ic_participant_active", bundle: .module)
    static let videoCallParticipantInactiveIcon = Image("ic_participant_inactive", bundle: .module)
    static let videoCallQnAActiveIcon = Image("ic_qna_active", bundle: .module)
    static let videoCallQnAMenuInactiveIcon = Image("ic_qna_inactive", bundle: .module)
    static let videoCallSwitchCameraActiveIcon = Image("ic_switch_active", bundle: .module)
    static let videoCallSwitchCameraInactiveIcon = Image("ic_switch_inactive", bundle: .module)
    static let videoCallVideoCameraActiveIcon = Image("ic_video_active", bundle: .module)
    static let videoCallVideoCameraInactiveIcon = Image("ic_video_inactive", bundle: .module)
    static let videoCallMicOffStrokeIcon = Image("ic_mic_off_stroke", bundle: .module)
    static let videoCallMicOnStrokeIcon = Image("ic_mic_on_stroke", bundle: .module)
    static let videoCallVideoOffStrokeIcon = Image("ic_video_off_stroke", bundle: .module)
    static let videoCallVideoOnStrokeIcon = Image("ic_video_on_stroke", bundle: .module)
    static let videoCallClockWhiteIcon = Image("ic_clock_white", bundle: .module)
    static let videoCallLiveWhiteIcon = Image("ic_live_white", bundle: .module)
    static let videoCallFlipCameraWhiteIcon = Image("ic_flip_camera_white", bundle: .module)
    static let videoCallChatIcon = Image("ic-bubble-chat", bundle: .module)
    static let videoCallMoreMenuNewIcon = Image("ic-menu-icon", bundle: .module)
    static let videoCallRaiseHandActive = Image("ic-raise-on-icon", bundle: .module)
    static let videoCallRaiseHandInactive = Image("ic-raise-off-icon", bundle: .module)
    static let videoCallQuestionIcon = Image("ic-question-icon", bundle: .module)
    static let videoCallPollingIcon = Image("ic-polling", bundle: .module)
    static let videoCallNewParticipantIcon = Image("ic-participant-new", bundle: .module)
    static let videoCallRecordVideoIcon = Image("ic-record-video", bundle: .module)
    static let videoCallPictureInPictureIcon = Image("ic-mini-view", bundle: .module)
    static let videoCallInformationIcon = Image("ic_information", bundle: .module)
}
