disabled_rules:
- trailing_whitespace
- multiple_closures_with_trailing_closure
- colon
- identifier_name
- implicit_getter
- switch_case_alignment
- redundant_string_enum_value
- control_statement
- empty_enum_arguments
opt_in_rules:
- empty_count
- empty_string
excluded:
- Carthage
- Pods
- SwiftLint/Common/3rdPartyLib
line_length:
    warning: 250
    error: 300
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true
function_body_length:
    warning: 300
    error: 500
function_parameter_count:
    warning: 6
    error: 8
type_body_length:
    warning: 800
    error: 1000
file_length:
    warning: 800
    error: 1000
    ignore_comment_only_lines: true
cyclomatic_complexity:
    warning: 25
    error: 35
reporter: "xcode"
