//
//  Image+Dinotis.swift
//  DinotisApp
//
//  Created by Gus Adi on 27/11/21.
//

import SwiftUI

extension Image {
	enum Dinotis {
		// MARK: - Sample Image
		static let exampleBCA = Image("example-bca")
		static let exampleUserImage = Image("example-img")
		
		// MARK: - Image
		static let appleLogo = Image("applelogo")
		static let googleLogo = Image("googlelogo")
		static let biodataImage = Image("biodata-img")
		static let changeEmailImage = Image("change-email-img")
		static let emailVerificationImage = Image("email-verif-img")
		static let emptyScheduleImage = Image("empty-schedule-img")
		static let forgotPasswordImage = Image("forgot-pass-img")
		static let popoutImage = Image("img-popout")
		static let splashScreenImage = Image("img-splash-screen")
		static let userTypeImage = Image("img-user-type")
		static let linearGradientBackground = Image("linear-gradient-bg")
		static let talentLoginImage = Image("login-talent-img")
		static let userLoginImage = Image("login-user-img")
		static let dinotisLogoFulfilled = Image("logo-dinotis-1")
		static let logoutImage = Image("logout-img")
		static let paymentSuccessImage = Image("payment-success-img")
		static let removeUserImage = Image("remove-user-img")
		static let searchNotFoundImage = Image("search-not-found-img")
		static let splashScreenBackground = Image("Splashscreen-bg")
		static let timeoutImage = Image("time-out-img")
		static let userTypeBackground = Image("user-type-bg")
		static let whatsappLogo = Image("whatsapp-img")
		static let otpVerificationImage = Image("otp-verification-img")
		static let resetPasswordIllustration = Image("reset-password-illustration")
        static let twilioBackground = Image("twilio-background")
		
		// MARK: - Icon
		static let chevronLeftCircleIcon = Image("chevron-left-circle")
		static let reportButtonIcon = Image("ic-btn-report")
		static let walletButtonIcon = Image("ic-btn-wallet")
		static let calendarIcon = Image("ic-calendar")
		static let changePassButtonIcon = Image("ic-change-pass")
		static let arrowBackIcon = Image("ic-chevron-back")
		static let chevronBottomIcon = Image("ic-chevron-bottom")
		static let clockIcon = Image("ic-clock")
		static let copyIcon = Image("ic-copy")
		static let customerServiceButtonIcon = Image("ic-cust-service")
		static let handPickedDebitCardIcon = Image("ic-debit-card")
		static let handPickedDebitCardWithRoundedRectangle = Image("ic-debit-rounded")
		static let editPhotoIcon = Image("ic-edit-photo")
        static let addPhotoBanner = Image("ic-pluss")
		static let editProfileButtonIcon = Image("ic-edit-profile")
		static let feeTalentIcon = Image("ic-fee-talent")
		static let linkedIcon = Image("ic-linked")
		static let lockIcon = Image("ic-lock")
		static let logoutButtonIcon = Image("ic-logout")
		static let magnifyingIcon = Image("ic-magnifying-glass")
		static let mailIcon = Image("ic-mail")
		static let menuDeleteIcon = Image("ic-menu-delete")
		static let menuEditIcon = Image("ic-menu-edit")
		static let notificationBadgeIcon = Image("ic-notif-badge")
		static let notificationEmptyIcon = Image("ic-notif-empty")
		static let notificationFilledIcon = Image("ic-notif-home")
		static let pencilIcon = Image("ic-pencil")
		static let peopleCircleIcon = Image("ic-people-circle")
		static let plusIcon = Image("ic-plus")
		static let priceTagIcon = Image("ic-pricetag")
		static let radioSelectedIcon = Image("ic-radio-select")
		static let radioUnselectIcon = Image("ic-radio-unselect")
		static let reportIcon = Image("ic-report")
		static let sessionIcon = Image("ic-session")
		static let accountVerifiedIcon = Image("ic-verif-acc")
		static let verifiedCorrectIcon = Image("ic-verified")
		static let videoCallFormIcon = Image("ic-vidcall-form")
		static let videoCallWithRoundedRectangleIcon = Image("ic-video-conf")
		static let withdrawTalentIcon = Image("ic-withdraw-talent")
		static let exclamationCircleIcon = Image("icn-exclamation-circle")
		static let userCircleFillIcon = Image("user-circle-fill")
		static let phoneIcon = Image("ic-phone")
		static let scheduleButtonBackground = Image("bg-schedule-button")
		static let sheduleIllustrate = Image("schedule-image")
		static let buttonScheduleChevronIcon = Image("button-schedule-chevron-ic")
		static let categoryCardBackground = Image("category-card-bg")
		static let filledChecklistIcon = Image("filled-checklist")
		static let emptyChecklistIcon = Image("empty-checklist")
		static let startLiveIllustration = Image("startLiveIllustration")
		static let lineClockIcon = Image("line-clock-icon")
		static let sendMessageIcon = Image("send-message-icon")
		static let maximizeIcon = Image("maximize-icon")
		static let suitcaseIcon = Image("ic-suitcase")
		static let shareIcon = Image("ic-share-circle-fill")
		static let personPhoneIcon = Image("ic-person-phone")
		static let previewProfileIcon = Image("profile-preview-button-icon")
		static let addPasswordIllustration = Image("add-password-illustration")
		static let stepCheckmark = Image("step-checkmark")
		static let stepThree = Image("step-three")
		static let stepFour = Image("step-four")
		static let stepOne = Image("step-one")
		static let stepTwo = Image("step-two")
		static let noticeIcon = Image("ic-notice")
		static let closeGroupCallIcon = Image("ic-close-group-call")
		static let menuGroupCallIcon = Image("ic-menu-group-call")
		static let mutedGroupCallIcon = Image("ic-muted-group-call")
		static let offcamGroupCallIcon = Image("ic-offcam-group-call")
		static let oncamGroupCallIcon = Image("ic-oncam-group-call")
		static let raiseGroupCallIcon = Image("ic-raised-group-call")
		static let unmuteGroupCallIcon = Image("ic-unmute-group-call")
		static let unraisedGroupCallIcon = Image("ic-unraised-group-call")
		static let switchCamGroupCallIcon = Image("ic-switch-group-call")
		static let helpGroupIcon = Image("ic-help-group")
		static let liveChatGroupIcon = Image("ic-live-chat-group")
		static let participantGroupIcon = Image("ic-participant-group")
		static let questionBoxGroupIcon = Image("ic-question-box")
		static let coinIcon = Image("ic-coin")
		static let coinInIcon = Image("ic-coin-in")
		static let coinOutIcon = Image("ic-coin-out")
		static let emptyCoinIllustration = Image("empty-coin-illustration")
		static let deleteAccountIcon = Image("ic-delete-acc-btn")
		static let otpWhatsappIcon = Image("ic-whatsapp-otp")
		static let otpSmsIcon = Image("ic-sms")
        static let redPricetagIcon = Image("ic-pricetag-red")
        static let redCameraVideoIcon = Image("ic-red-camera-video")
        static let formNoteIcon = Image("ic-form-note")
        static let messageIcon = Image("ic-message")
        static let xmarkIcon = Image("ic-xmark")
        static let flatPlaneButtonIcon = Image("ic-flat-plane")
        static let rateCardIcon = Image("ic-ratecard")
        static let newBadgeIcon = Image("ic-new-badge")
	}

	enum dinotisV3 {
		static let splashscreenImage = Image("img-splashscreen-v3")
		static let splashscreenBackgroundImage = Image("splashscreen-bg-img")
	}
	
	static func base64Image(with url: String) -> Image {
		let temp = url.replacingOccurrences(of: "data:image/png;base64,", with: "")
		guard let data = Data(base64Encoded: temp, options: .ignoreUnknownCharacters) else { return Image("") }
		guard let uiImage = UIImage(data: data) else { return Image("") }
		return Image(uiImage: uiImage)
	}
}
